### ISSUE TITLE
When I test like this  "$:python test.py", show "TypeError: ONNX node of type Pad is not supported.

### ISSUE THREAD

**Issue by Johnson13** [MTlab/onnx2caffe#5]
Hello:
    I have an error when I test the test.py.  Details:

```
root@524c09ef713d:/home/onnx2caffe/onnx2caffe-master# python test.py
export broadcast_mul onnx model ...
graph(%0 : Float(1, 3, 4, 4)
      %1 : Float(128, 3, 3, 3)
      %2 : Float(128)
      %3 : Float(128)
      %4 : Float(128)
      %5 : Float(128)
      %6 : Float(128)
      %7 : Long()) {
  %8 : Float(1, 128, 4, 4) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%0, %1, %2), scope: broadcast_mul/Sequential[conv1]/Conv2d[0]
  %9 : Float(1, 128, 4, 4) = onnx::BatchNormalization[epsilon=1e-05, momentum=1](%8, %3, %4, %5, %6), scope: broadcast_mul/Sequential[conv1]/BatchNorm2d[1]
  %10 : Float(1, 128, 4, 4) = onnx::Relu(%9), scope: broadcast_mul/Sequential[conv1]/ReLU[2]
  %11 : Tensor = onnx::Pad[mode="constant", pads=[0, 0, 0, 0, 0, 0, 0, 0], value=0](%10), scope: broadcast_mul/AvgPool2d[poo1]
  %12 : Float(1, 128, 1, 1) = onnx::AveragePool[kernel_shape=[4, 4], pads=[0, 0, 0, 0], strides=[4, 4]](%11), scope: broadcast_mul/AvgPool2d[poo1]
  %13 : Float(1, 128, 4, 4) = onnx::Mul(%10, %12), scope: broadcast_mul
  return (%13);
}

converting broadcast_mul to caffe ...
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    caffe_model = convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "/home/onnx2caffe/onnx2caffe-master/convertCaffe.py", line 54, in convertToCaffe
    err.unsupported_op(node)
  File "/home/onnx2caffe/onnx2caffe-master/onnx2caffe/_error_utils.py", line 36, in unsupported_op
    "ONNX node of type {} is not supported.\n".format(node.op_type,)
**TypeError: ONNX node of type Pad is not supported.**
```
How can I fix this error?  
Thanks.

**Comment by YukiNagato** [comment]
Hi, are you using pytorch >0.4? This project only support pytorch 0.4.0.

**Comment by Johnson13** [comment]
Hi，It works. Thank you so much!
